powerjob:
  worker:
    # Akka port, default is 27777
    akka-port: 27777
    # Max length of appended workflow context . Appended workflow context value that is longer than the value will be ignore.
    max-appended-wf-context-length: 4096
    # Max length of result. Results that are longer than the value will be truncated.
    max-result-length: 16384
    # Address of PowerJob-server node(s). Ip:port or domain. Multiple addresses should be separated with comma.
    server-address: chronos-server.qzgw.163.internal
    # Store strategy of H2 database. disk or memory. Default value is disk.
    store-strategy: memory

datasource:
  chronos:
    support:
      jdbcUrl: jdbc:mysql:loadbalance://192.168.198.10:4000,192.168.198.11:4000,192.168.198.12:4000/chronos_support?loadBalanceAutoCommitStatementThreshold=5&loadBalancePingTimeout=1000&loadBalanceBlocklistTimeout=60000&loadBalanceValidateConnectionOnSwapServer=true
      username: chronos_support
      password: s91QWuCHQr
      poolName: chronos-support-datasource
      maximum-pool-size: 300
      minimum-idle: 50

#[eureka]
eureka:
  instance:
    metadata-map:
      env: release
  client:
    serviceUrl:
      defaultZone: http://10.110.47.50:1111/eureka/,http://10.110.47.51:1111/eureka/

feign:
  httpclient:
    enabled: true
    max-connections: 500
    max-connections-per-route: 200
    connection-timeout: 3000

logging:
  config: classpath:logback/logback-release.xml


notify:
  api:
    url: mpserv-notify.qzgw.163.internal

srvupgrade:
  baseUrl: http://10.110.46.15:18087